#!/bin/bash

#SBATCH --job-name=mapping
#SBATCH --account=vasccell
#SBATCH --nodes=1
#SBATCH --cpus-per-task=28
#SBATCH --mem=40G
#SBATCH --time=23:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=cs806@leicester.ac.uk
#SBATCH --output=%x.out
#SBATCH --error=%x.err
#SBATCH --export=NONE

cd $SLURM_SUBMIT_DIR


date

# Load modules
module load star/2.7.10b-m3zkpic

# #step 1 - generate genome index
#STAR --runMode genomeGenerate --runThreadN 28 --genomeDir /scratch/vasccell/cs806/exprPhenoData/GRCh38_STARindex --genomeFastaFiles /scratch/vasccell/cs806/exprPhenoData/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa --sjdbGTFfile /scratch/vasccell/cs806/exprPhenoData/Homo_sapiens.GRCh38.100.gtf --sjdbOverhang 89

# Confirm the fastq extension is correct.
find /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/rawReads -type f -name "*fastq.gz" -exec basename {} \; | sed 's/fastq.gz//g' > /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/brbSeq2_Scripts/allSeq2.txt


while IFS= read -r F
do

  R1=${F}fastq.gz
  R2=${F}_2.fq.gz
  STAR --runMode alignReads --runThreadN 28 --genomeDir /scratch/vasccell/cs806/exprPhenoData/GRCh38_STARindex --readFilesIn /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/rawReads/$R1 --readFilesCommand zcat --sjdbOverhang 89 --outFileNamePrefix /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/mappedReads/$F --twopassMode Basic --quantMode TranscriptomeSAM GeneCounts --outSAMunmapped Within --outSAMstrandField intronMotif --outFilterIntronMotifs RemoveNoncanonical --outFilterType BySJout --limitSjdbInsertNsj 2000000  

#echo $F
#echo $R1
#echo $R2

done < /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/brbSeq2_Scripts/allSeq2.txt

source ~/miniconda3/bin/activate mypython311
multiqc /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/mappedReads -f --interactive -o /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/mappedReads

date


