#!/bin/bash

#SBATCH --job-name=salmonQuant
#SBATCH --account=vasccell
#SBATCH --nodes=1
#SBATCH --cpus-per-task=14
#SBATCH --mem=10G
#SBATCH --time=02:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=cs806@leicester.ac.uk
#SBATCH --output=%x.out
#SBATCH --error=%x.err
#SBATCH --export=NONE

cd $SLURM_SUBMIT_DIR

module load salmon/1.10.2-5pennjh
module load R

# Make decoy
# grep "^>" <(gunzip -c GRCm38.primary_assembly.genome.fa.gz) | cut -d " " -f 1 > decoys.txt
# sed -i.bak -e 's/>//g' decoys.txt
# cat gencode.vM23.transcripts.fa.gz GRCm38.primary_assembly.genome.fa.gz > gentrome.fa.gz

# Index with decoy
# salmon index -t gentrome.fa.gz -d decoys.txt -p 12 -i salmon_index --gencode


salmon index -t /scratch/vasccell/cs806/exprPhenoData/gencode.v44.transcripts.fa.gz -i /scratch/vasccell/cs806/exprPhenoData/gencode.v44.transcripts_index 
salmon index -t /scratch/vasccell/cs806/exprPhenoData/Homo_sapiens.GRCh38.cdna.all.fa.gz -i /scratch/vasccell/cs806/exprPhenoData/Homo_sapiens.GRCh38.cdna.all_index

# Confirm the fastq extension is correct.
find /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/rawReads -type f -name "*.fastq.gz" -exec basename {} \; | sed 's/.fastq.gz//g' > /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/brbSeq2_Scripts/allSeq3.txt

#### Quant with GENCODE
while IFS= read -r F
do
  echo "Processing $F"
  R1=${F}.fastq.gz
  R2=${F}_2.fq.gz
  salmon quant -i /scratch/vasccell/cs806/exprPhenoData/gencode.v44.transcripts_index -l A -r /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/rawReads/$R1 -p 14 --validateMappings -o /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/salmonQuant/$F

done < /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/brbSeq2_Scripts/allSeq3.txt

##### Quant with ENSEMBL
while IFS= read -r F
do
  echo "Processing $F"
  R1=${F}fastq.gz
  R2=${F}_2.fq.gz
  salmon quant -i /scratch/vasccell/cs806/exprPhenoData/Homo_sapiens.GRCh38.cdna.all_index -l A -r /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/rawReads/$R1 -p 14 --validateMappings -o /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/salmonQuant/$F
  
done < /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/brbSeq2_Scripts/allSeq3.txt

Rscript /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/brbSeq2_Scripts/salmonQuant_txi.R

module purge
source ~/miniconda3/bin/activate mypython311
multiqc /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/salmonQuant -f --interactive -o /lustre/alice3/scratch/vasccell/cs806/brbSeq/brbSeq2/salmonQuant
